language: node_js
node_js:
  - '5'
notifications:
  email:
    on_success: never
services:
  - docker
before_install:
  - docker build -t naaaathan11 .
  - docker ps -a
after_success:
  - >-
    if [ "$TRAVIS_BRANCH" == "master" ]; then

    docker login -u="$HEROKU_USERNAME" -p="$HEROKU_PASSWORD"
    registry.heroku.com;

    docker build -t registry.heroku.com/naaaathan11/web .;

    docker push registry.heroku.com/naaaathan11/web;

    fi
